# Generated by Django 6.0.1 on 2026-01-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='color',
        ),
    ]
